- model2/include/hist_schedule.sch
Keyword WRFTPLT added to schedule section file used by all 10 decks. 
WRFTPLT is used to request simulation/modelling of RFT's for a selected well. Simulation results for these RFTs are stored in the RFT file. RFTs are used in the majority of history matching studies and these are very important data.
> model2 - updated schedule section  for all cases 0_BASE to 9_EDITNNC

- udq_actionx/include/example_summary.txt
- wtest/include/example_summary.txt
- wtest/include/example_summary_gasmod.txt
these will be different in different runs,
leading to files always being updated when update_data is invoked.
ref https://github.com/OPM/opm-common/pull/996
@joakim-hove 
thanks to @bska for hand holding - i know more about these file formats now.
> fixed: disable TCPU and TCPUDAY

- spe9/SHORT.SCH
- spe9/SPE9_CP_SHORT.UNRST
This is a preparation step for: https://github.com/OPM/opm-common/issues/1396
As part of https://github.com/OPM/opm-common/issues/1396 there will be a stronger coupling between the input deck and the restart file - in the case of a restarted case the restart file can semantically be perceived as an include file.
The first commit makes sure that the date we are restarting from is explicitly mentioned in the Schedule section - this is *highly recommended* in the manual. The second commit makes the restart file available (as a symlink) from the location of the input file.
> Update sp9 restart

- spe1/SPE1CASE2_ACTNUM_RESTART.DATA
When restarting with the `SKIPREST` keyword you *really* should have the restart date in the deck.
> Add DATES keyword for restart date in testdata

- model2/include/summary.inc
See this [comment](https://github.com/OPM/opm-common/pull/1656#issuecomment-607233604).
The performance related keywords are removed because they are not really suitable for regression testing - but we do not support them either.
The DATE keyword is removed because we do not support it.
So - since the keywords removed in this PR are not supported anyway I would say we could safely run a update data right away - on this particular PR. I will initiate the process and let others double check my logic and (hopefully) merge.
> Remove DATE and performance related summary keywords

- udq_actionx/UDQ_WCONPROD.DATA
This is a minor (result wise noop) change to the `UDQ_WCONPROD` testcase to get a regression test for the new capability introduced here: https://github.com/OPM/opm-common/pull/1763
> Use WELTARG + UDA for one of the wells in UDQ WCONPROD testcase

- pinch/PINCH_MULTZ_ALL_BARRIER.DATA
* introduces a vertical flow barriere with MULTZ=0.0 for a pinched grid cell
This case is equal to case PINCH_MULTZ_ALL except for the addition 
```
EQUALS
'MULTZ' 0.0 4* 10 10 /
/
```
Layer 10 is collapsed (hence inactive), but when used together with PINCH (item5 ALL) this should act as a barrier for vertical flow.  Current version of Flow is not honoring this flow barrier
> Adding one more test case which th PINCH ITEM4=ALL

- norne/INCLUDE/B1H_RE-PERF.SCH
- norne/NORNE_ATW2013_B1H_RE-PERF.DATA
Test based on NORNE_ATW2013. This model included only one well (B-1H) which original sequence of perforation and then additional perforation. 
WELSPECS is set up with item5 (reference depth) defaulted, which means that this depth is defined from cell center depth of first connection according to COMPORD. 
Notice that reference depth **should not** be reset (updated) when additional perforations (in this case shallower) are added.   
Notice that bottom hole pressure (WBHP:*) is reported at reference depth.
> Re-perf well, don't update ref depth

- model2/0B_WELPI_MODEL2-MSW.DATA
- model2/include/hist_schedule_welpi_msw_def-ro_compdat.sch
This pull request contains a test-dataset for test of the WELPI keyword in Eclipse for multisegment wells. In order to achieve a better test dataset, the water-oil-contact was moved in both: 
0B_WELPI_MODEL2.DATA and 
0B_WELPI_MODEL2-MSW.DATA
compared to the original test dataset for standard well model wells. 
The multisegment wells are similar/comparable to the standard wells.
> Test dataset for test of the WELPI keyword

- model3/4_NUMAQ_MODEL3.DATA
It seems like include paths for this file should be corrected the same way as it is in other DATA files in the same folder.
Thanks,
> Fix include paths for 4_NUMAQ_MODEL3.DATA.

- norne/NORNE_ATW2013_B1H_RE-PERF.DATA
Disable tracer summary output for `norne/NORNE_ATW2013_B1H_RE-PERF.DATA`.
A bit unclear whether this is currently needed also for other norne-related DATA-files.
> Temporarily disable tracer summary output.

- aquifer-oilwater/2D_OW_CTAQUIFER_RESTART.DATA
These do not exist in the base run and cause regression failures.
> Remove Summary Vectors Particular to Restart Case

- norne/plotwells.sh
newer latex has changed the default output filename to texput.dvi,
not article.dvi.
> fixed: norne well output

- lgr/SPE1CASE1_CARFIN.DATA
Simplification following on the discussion on not given priority to redefining grid properties in a LGR.
> Simplify SPE1CASE1_CARFIN.DATA

- wconprod/WCONPROD-01.DATA
- wconprod/WCONPROD-02.DATA
- wconprod/WCONPROD-03.DATA
- wconprod/WCONPROD-04.DATA
- wconprod/WCONPROD-05.DATA
- wconprod/WCONPROD-06.DATA
- wconprod/WCONPROD-07.DATA
- wconprod/WCONPROD-08.DATA
- wconprod/WCONPROD-09.DATA
- wconprod/WCONPROD-10.DATA
- wconprod/WCONPROD-11.DATA
- wconprod/WCONPROD-12.DATA
- wconprod/WCONPROD.DATA
- wconprod/WCONPROD.md
The default tokens of 1* and '' should behave the same; however, the actual values used when WCONPROD(TARGET) is defaulted is variable, as outlined below:
If the well is not under group control, then WCONPROD(TARGET) is set to the first non-defaulted hydrocarbon rate (ORAT, GRAT, LIQ, RESV). If all rates are defaulted and BHP is entered, then the BHP is used. It is assumed that if the BHP is defaulted as well, and THP has been entered, then THP would be used (this configuration has not been tested). Finally, if all parameters are defaulted, then the default value of BHP (14.70 psia) will be used combined with BHP control. In all the above scenarios the well has been declared as open, that is WCONPROD(STATUS) is set to OPEN.
If, and only if, the well’s group parameters have been defined …
> WCONPROD(TARGET) Tests 

- spe1/SPE1CASE2_KRNUM.DATA
This test is created from SPE1CASE2.DATA by adding a second saturation function that has a lower oil relative permeability. This saturation function is used in the X-direction by applying the KRNUMX keyword. See https://github.com/OPM/opm-common/pull/3113 for more information.
> Adds a test case for testing KRNUM

- spe1_precsalt/SPE1CASE1_PRECSALT.DATA
More precise conversion of 2170 kg/m3 to lb/ft3.
> Improve unit conversion

- pinch/PINCH_MULTZ-_ALL.DATA
- pinch/PINCH_MULTZ-_ALL_BARRIER.DATA
This PR includes two new test cases with PINCH item 5 = ALL and keyword MULTZ-. 
- PINCH_MULTZ-_ALL.DATA
- PINCH_MULTZ-_ALL_BARRIER.DATA
The second model (multz- barrier) is currently not supported with Flow, hence the simulator will need a fix before this can be put under regression testing.
These two new test cases are similar to existing cases [PINCH_MULTZ_ALL](https://github.com/OPM/opm-tests/blob/master/pinch/PINCH_MULTZ_ALL.DATA) and [PINCH_MULTZ_ALL_BARRIER](https://github.com/OPM/opm-tests/blob/master/pinch/PINCH_MULTZ_ALL_BARRIER.DATA). The only difference is that the new test cases are using MULTZ- instead of MULTZ.
> test cases with pinch all and multz-

- spe10/SPE10-MOD01-01.DATA
- spe10/SPE10-MOD01-02.DATA
- spe10/SPE10-MOD01-03.DATA
- spe10/SPE10-MOD01-04.DATA
- spe10/SPE10-MOD02-01.DATA
- spe10/SPE10-MOD02-02.DATA
Comment out the NONNC keyword in SPE10 cases, as the keyword is not supported, and results in the cases not running.
> Comment out NONNC in SPE10 Cases

- actionx/ACTIONX_GCONPROD.DATA
- spe9group/SPE9_CP_GROUP.DATA
- spe9group/SPE9_CP_GROUP_RESV.DATA
Only RATE is supported in GCONPROD item 7. Notice that NONE is default, hence default not supported.
The current behavior of OPM Flow is that the simulator will handle item 7 input in GCONPROD as if this was RATE, independent of what the input actually is. Hence simulation results (all summary vectors and solution data in restart file ) will not changed due to this PR. However, this will modify output to some of the restart arrays (example IGRP). An update of reference solutions are therefor required. 
This is a preparation for a PR in opm-simulators which will stop the simulation if input different that RATE is given.
> Fixed data decks with GCONPROD item 7 not set to RATE

- aquifers/AQUFLUX-02.DATA
referring to discussion in https://github.com/OPM/opm-simulators/pull/4520 . 
This case provide more testing capacity and testing some different setup regarding the AQUFLUX. Especially, this case contains two aquifers and they are defined purely in the SCHEDULE section.  And it also revealed some bugs when developing PR  https://github.com/OPM/opm-simulators/pull/4520  when coming to parallel restart.
> adding a new AQUFLUX case

- cskin/CSKIN-02.DATA
- cskin/CSKIN-03.DATA
- cskin/CSKIN-04.DATA
- cskin/CSKIN-05.DATA
The default group name gave errors in OPM Flow.
Related to opm-common and opm-simulators PRs: https://github.com/OPM/opm-common/pull/3681 and https://github.com/OPM/opm-simulators/pull/4871
> Fix group name in WELSPECS

- welspecs/TEST3_WS.DATA
Updated test case with extended `WELSPECS`. Illegal spaces in item number 2 in keyword `WELSPEC` gives error message
```
Error: Problem with keyword WELSPECS
In TEST3_WS.DATA line 314
Illegal space in   B1 when defining WELL/GROUP.
```
> fix illegal spaces in WELSPECS keyword

- regset/SPE1CASE2_REGSET.DATA
Mostly to keep cases with "long" region set names like
```
FIPABCDE
```
working alongside summary vector names of the form
```
ROIP_ABC
```
> Add Test Case for Summary Vectors With Short Region Set Names

- model4/MOD4_GRP.DATA
- model4/MOD4_GRP_GEFAC.DATA
- model4/MOD4_GRP_INPLACE_RESTART.DATA
- model4/MOD4_GRP_RESTART.DATA
- model4/MOD4_UDQ_ACTIONX.DATA
With this implemented, we want to remove the potential source of instability in regression tests.
Sidestream of https://github.com/OPM/opm-simulators/pull/5054
> changed: remove CONV from RST output

- gconprod/T2G.DATA
- gconprod/T2O.DATA
Number of pvt tables and TABDIMS did not match. Also ROCK was duplicated, both in include/PVT-WET-GAS and in the deck.
> Fix number of PVT tables

- pyaction/pyaction_next_insert_kw.py
With this, you can pipe the simulation output and the python printouts are the correct spot
> Use opm_embedded.OpmLog.info instead of print in the python functions

- lgr/SPE1CASE1_CARFIN_FLEX.DATA
This test is a modification of SPE1CASE1_CARFIN.DATA only in the CARFIN code, with the goal of illustrating the improvement in refinement given in OPM/opm-grid#723.  It might not have a physical relevance.
> Add test to illustrate improvement in CARFIN keyword

- norne/NORNE_ATW2013.DATA
- norne/NORNE_ATW2013_1A_MSW.DATA
- norne/NORNE_ATW2013_1A_STDW.DATA
- norne/NORNE_ATW2013_1B_MSW.DATA
- norne/NORNE_ATW2013_1B_MSW_NO_XFLOW.DATA
- norne/NORNE_ATW2013_1B_STDW.DATA
- norne/NORNE_ATW2013_2A_MSW.DATA
- norne/NORNE_ATW2013_2A_STDW.DATA
- norne/NORNE_ATW2013_2B_MSW.DATA
- norne/NORNE_ATW2013_2B_STDW.DATA
- norne/NORNE_ATW2013_3A_MSW.DATA
- norne/NORNE_ATW2013_3A_STDW.DATA
- norne/NORNE_ATW2013_3B_MSW.DATA
- norne/NORNE_ATW2013_3B_STDW.DATA
- norne/NORNE_ATW2013_3C_MSW.DATA
- norne/NORNE_ATW2013_3C_STDW.DATA
- norne/NORNE_ATW2013_4A_MSW.DATA
- norne/NORNE_ATW2013_4A_STDW.DATA
- norne/NORNE_ATW2013_4B_MSW.DATA
- norne/NORNE_ATW2013_4B_STDW.DATA
- norne/NORNE_ATW2013_4C_MSW.DATA
- norne/NORNE_ATW2013_4C_STDW.DATA
- norne/NORNE_ATW2013_4D_MSW.DATA
- norne/NORNE_ATW2013_4D_STDW.DATA
- norne/NORNE_ATW2013_4E_MSW.DATA
- norne/NORNE_ATW2013_4E_STDW.DATA
- norne/NORNE_ATW2013_B1H_RE-PERF.DATA
- norne/NORNE_ATW2013_RESTART.DATA
Hello everyone,
The unsupported keyword OPTIONS and the keyword PIMULTAB were being used in Norne cases. I commented these keywords and the PIMULTAB related keyword PIMTDIMS.
Here is the error message screenshot that I got before comment there keywords.
Flow version 2024.10-pre
> Keywords (OPTIONS and PIMULTAB) not supported were commented.

- udq_actionx/UDQ_REG-02.DATA
There is a maximum length = 128 (16 x 8). This is related to the restart format.
This test case includes the UDQ **FU_TEST** which holds exactly 128 characters. OPM flow is currently not supporting this deck. The simulation stops and the following Error message is reported.
```
ERROR: Uncaught std::exception when running tasklet: DEFINE expression for UDQ FU_TEST is too long.
Number of characters 164 exceeds upper limit of 128.
Expression: (ROIP_RE2 '2') / (FURE2) * (0.3 * (RGPR_RE2 '1') + (RGPR_RE2 '2') + (RGPR_RE2 '3')) / (GEFF 'TEST') * (1 + FUGASX) + ((1 * TIME * TIME - 75 * TIME + 1250) * 50.123).
```
Notice that if you remove keyword RPTRST in the Solution section, the simulation will run and simulation results are good.
> Test case with a UDQ holding maximum string length (input)

- actionx/ACTIONX_WCONINJH.DATA
This will tests the action in a normal time step (Jan 7. Previously the ACTIONX was triggered at a report step (Jan 5)
> Move date of ACTIONx for WCONINJH away from end of report step.

- spe1_precsalt/GASCONDENSATE_VAPWAT_PRECSALT.DATA
Closes https://github.com/OPM/opm-tests/issues/1408
> Adding missing default tables in GASCONDENSATE_VAPWAT_PRECSALT.DATA
