- spe5_ehystr2_0/SPE5CASE_GAS_EHYSTR2_0.DATA
- spe5_ehystr2_1/SPE5CASE_SOLVENT_EHYSTR2_1.DATA
0:  Drainage curve is used or the wetting phase
1:  Imbibition curve is used for the wetting phase 
The second test also test the combination solvent + hysteresis.
> Add test cases with Carlson’s hysteresis model

- spe1_foam/SPE1FOAM.DATA
The test case is based on SPE1CASE2 and is completely artificial. No attempts have been made to make it realistic at this point.
> Add data file for small foam test case.

- spe9/SPE9_CP.DATA
- spe9/SPE9_CP_GROUP.DATA
- spe9_solvent/SPE9_CP_SOLVENT_CO2.DATA
See: https://github.com/OPM/opm-common/pull/931
> Remove trailing space in wellname in WELSPCS keyword

- wsegvalv/BASE_MSW_WSEGVALV.DATA
- wsegvalv/include/prod1_msw_wsegvalv_data.inc
- wsegvalv/include/prod1_well_data.inc
Input data created with software Resinsight. Equal spacing between inflow devices.
> Updated test case for WSEGVALV, more realistic use case

- norne/plotwells.sh
I'm not sure how this is run on jenkins but this is running for me locally at least
> plotwells.sh in norne now using summary

- model2/include/hist_schedule.sch
> Add -- $REPORT_STEP to DATES keywords - to simplify debugging

- model2/include/hist_schedule.sch
The dataset had comments starting in column 8 - that could create problems
> Ensure that comment starts in column 9

- wsegvalv/BASE_MSW_WSEGVALV.DATA
- wsegvalv/include/prod1_msw_data.inc
- wsegvalv/include/summary.inc
The previous version of this model had issues (which is not resolved) not related to wsegvalv. This version of the model is a simplified version of the previous version. 
This model still have significant impact of the inflow device (keyword WSEGVALV).
> updated test model for wsegvalv

- model4/MOD4_GRP.DATA
- model4/MOD4_UDQ_ACTIONX.DATA
- model4/include/test3_satf.inc
* redused memory requirements, relevant for Eclipse simulator
* modified EQUIL records item9
> update of model4

- model2/3_A_MPI_MULTFLT_SCHED_MODEL2.DATA
- model2/include/hist_schedule_multflt.sch
Added one case based on the model2 case to test fault multipliers in the SCHEDULE section.
> Added case with fault multipliers in schedule section.

- model5/1_NETWORK_MODEL5.DATA
I guess some Tab were used while creating the tree - did not line up very nicely in my editor.
> White space changes to pretty print network tree

- model5/0_BASE_MODEL5.DATA
- model5/1_NETWORK_MODEL5.DATA
- model5/2_GLIFT_MODEL5.DATA
No functional changes. Reformatting to minimize spurious differences between cases (i.e. making
diff show functional changes).
Will self-merge immediately: there are no tests using this at the moment.
> Fix wrong group-tree ascii art, and reformat.

- spe9group/SPE9_CP_GROUP.DATA
to activate the output of the group report.
> adding WELSPECS to RPTSCHED in SPE9_CP_GROUP.DATA

- model4/MOD4_UDQ_ACTIONX_02.DATA
- model4/include/mod4_all_act02.sch
includes extra ACTIONX - 02,  which shuts water injector with lowest rate when total number of injector exceeds 6. Total number of injectors in the model is 8. Hence this action will be triggered twice.
> One extra test case for model4.

- pinch/FIVE.DATA
- pinch/FIVE_PINCH_GAP.DATA
- pinch/FIVE_PINCH_GAP2.DATA
- pinch/FIVE_PINCH_GAP3.DATA
- pinch/FIVE_PINCH_NOGAP.DATA
- pinch/FIVE_PINCH_NOGAP1.DATA
- pinch/FIVE_PINCH_NOGAP2.DATA
- pinch/FIVE_PINCH_NOGAP3.DATA
These simple tests are based on a vertical stack of 5 cells. There are tests with `PINCH GAP`, `PINCH NOGAP`, and without any `PINCH`. There are also reference solutions.
> Added small tests for PINCH functionality

- spe1/SPE1CASE2_THERMAL_WATVISC.DATA
Create test case for water dependency on temperature. This case run with with fix in PR OPM/opm-material#422..
> Test case for WATVISCT

- spe1_brine/SPE1CASE1_BRINE.DATA
Adjust the depths in the SALTVD table to the case.
> fix the depth in the SALTVD table

- model4/MOD4_GRP_RESTART.DATA
- model4/include/mod4_no_action.sch
Add restart case for `MOD4_GRP`
Test actually using this here: https://github.com/OPM/opm-simulators/pull/2729
> Mod4 restart

- aquifer-fetkovich/2D_FETKOVICHAQUIFER.DATA
- aquifer-oilwater/2D_OW_CTAQUIFER.DATA
modifying existing test casess 2D_FETKOVICHAQUIFER.DATA and 2D_OW_CTAQUIFER.DATA
requesting output of summary vectors
* AAQR - analytic aquifer rate
* AAQT - analytical aquifer cumulative
* AAQP - analytical aquifer pressure
Notice that these vectors are yet not supported with OPM Flow.
> adding aquifers related summary vectors

- model5/1_MAXVALUE_TRANZ.DATA
- model5/2_WLIFT_MODEL5.DATA
Putting back again comments that dropped out on the latest pull request.
> Added comments that were erronously removed.

- model5/0_BASE_MODEL5.DATA
- model5/1_MAXVALUE_TRANZ.DATA
- model5/2_WLIFT_MODEL5.DATA
- model5/include/summary.inc
added custom region FIPABC
added region summary vector for this custom region
> additional region summary vectors

- spe5/SPE5CASE1.DATA
> Add comment with report step number for TSTEP based deck

- model4/MOD4_GRP_INPLACE_RESTART.DATA
Add test deck for restart testing configured to be loaded inplace.
> Add restart testcase configured to be loaded in-place

- udq_actionx/ACTIONX_M1.DATA
> Add additional summary variables to ACTIONX_M1 testcase

- spe9group/SPE9_CP_GROUP_RESV.DATA
A test case that tests
1) RESV in prediction mode for producers
2) RESV for production groups
> Add RESV test case

- udq_actionx/UDQ_M1_RESTART.DATA
Add a test deck for restart testing of basic model with UDQ
> Add basic UDQ restart test

- spe1/SPE1CASE2_GASWATER.DATA
Test case for the  two-phase gas-water functionality. Test case is based on SPE1 CASE2.
> twophase gas-water test 

- model4/MOD4_GRP_GEFAC.DATA
Modified from MOD4_GRP. See L342.
> Add MOD4_GRP_GEFAC.DATA

- udq_actionx/PYACTION_WCONPROD.DATA
Make the UDA/UDQ definitions more explicit. Preparation for: https://github.com/OPM/opm-common/pull/2660
> Add UDQ ASSIGN statements for all the UDA values used in the deck

- actionx/ACTIONX.md
- actionx/ACTIONX_WTEST.DATA
Create ACTIONX_WTEST and Update Test Documentation
> Create ACTIONX_WTEST and Update Test Documentation

- co2store/CO2STORE_AQU.DATA
- co2store/CO2STORE_AQUCT.DATA
Note. None of this is supported at the moment, but I am working on it.
> Add test cases for CO2STORE and aquifers

- actionx/ACTIONX_COMPLUMP.DATA
- actionx/ACTIONX_GCONINJE.DATA
- actionx/ACTIONX_GCONPROD.DATA
- actionx/ACTIONX_GCONSUMP.DATA
- actionx/ACTIONX_GRUPTREE.DATA
- actionx/ACTIONX_UDQ.DATA
- actionx/ACTIONX_WCONINJE.DATA
- actionx/ACTIONX_WCONPROD.DATA
- actionx/ACTIONX_WEFAC.DATA
- actionx/ACTIONX_WELPI.DATA
- actionx/ACTIONX_WGRUPCON.DATA
- actionx/ACTIONX_WPIMULT.DATA
- actionx/ACTIONX_WTEST.DATA
While here, also ensure consistent EOL markings in version control.
> Remove EOL Whitespace From Simulation Input Files

- model5/4_GLIFT_MODEL5.DATA
GCONPROD exposes bug in the gasslift code.
>  Added GCONPROD

- model2/include/hist_schedule.sch
* request RFT for this well with keyword WRFTPLT
* secure that RFT report is not written for this well
> add well with no active connections

- spe1_precsalt/SPE1CASE1_PRECSALT.DATA
Add PERMFACT to input file description.
> Correct head

- udq_actionx/udq.py
Dwonstream of: https://github.com/OPM/opm-common/pull/2939
> Add actionx_callback argument to PYACTION run function

- spe1/SPE1CASE2_THERMAL.DATA
Test for https://github.com/OPM/opm-simulators/pull/3820
> Add BTCNFHEA to thermal case

- spe02/SPE02-RADIAL-01.DATA
- spe02/SPE02-RADIAL-02.DATA
- spe02/SPE02-RADIAL-03.DATA
- spe02/SPE02-RADIAL-04.DATA
- spe02/SPE02-RADIAL-05.DATA
- spe02/SPE02-SPIDER-01.DATA
- spe02/SPE02-SPIDER-02.DATA
- spe02/SPE02-SPIDER-03.DATA
- spe02/SPE02-SPIDER-04.DATA
- spe02/SPE02-SPIDER-05.DATA
- spe02/SPE02.md
Various radial and spider grid tests to check various input keywords based on SPE comparative solution number two (SPE02) .
Only two radial models run and none of the spider grid models run.
> SPE02 Radial and Spider Grid Tests

- wvfpexp/WVFPEXP-01.DATA
- wvfpexp/WVFPEXP-02.DATA
- wvfpexp/WVFPEXP-03.DATA
- wvfpexp/WVFPEXP-04.DATA
- wvfpexp/WVFPEXP-05.DATA
- wvfpexp/WVFPEXP-06.DATA
Fix mix capital/non-capital letters issue for include file names on Linux systems.
> WVFPEXP - Fix Mix Capital/Non-Capital Letters Issue

- diffusion/BO_DIFFUSE_CASE1.DATA
Case provided by Sebastian Bauer and Firdovsi Gasanzade at Geohydromodelling at Kiel University
The case exposed issue that is fixed in https://github.com/OPM/opm-models/pull/695.
> Add test case for h2 diffusion provided by Kiel University

- actionx/ACTIONX_WPIMULT.DATA
In preparation of adding a regression test based on this model.
While here, also switch to Unix EOL and switch of the "executable" bit.  Input data does not need to be marked as executable.
> Output Selected Connection Transmissiblity Factors

- spe1_precsalt/GASWATER_VAPWAT_PRECSALT.DATA
Delete unrelated keywords and FSIP.
> Update GASWATER case

- gaslift/GASLIFT-03.DATA
data file GASLIFT-03.DATA is not running with commercial simulator without these changes
> changing from \ to / in PATH and INCLUDE

- bc_lab/BC_LAB_DIRICHLET.DATA
Related to OPM/opm-simulators#4182
> add test case for dirichlet conditions

- norne/INCLUDE/BC0407_HIST01122006.SCH
WPITAB not supported and has been removed from the include file.
> Unsupported keyword

- spe1_precsalt/GASWATER_VAPWAT_PRECSALT.DATA
Related to https://github.com/OPM/opm-common/pull/2981
> Add salt density

- co2store/CO2STORE_GW.DATA
This add a test case for CO2STORE in combination with GAS and WATER
The should be added as a regression test once https://github.com/OPM/opm-simulators/pull/4292 and friends is merged.
> add co2store + gas + water case

- actionx/ACTIONX_WCONHIST.DATA
This test model is not supported by OPM but hopefully it should not be hard to fix this.
> Test case with ACTIONX and WCONHIST

- actionx/ACTIONX_WCONINJH.DATA
Currently not supported by OPM Flow
> Test case with ACTIONX and WCONINJH

- aquifers/AQUFLUX-01.DATA
This is a better test case for constant aquifer flux. This is copied of AQUNUM-01.DATA where the numerical aquifer is replaced with a constant flux aquifer.
> Update existing constant aquifer flux test model

- norne/NORNE_ATW2013_4C_MSW.DATA
> Comment out PIMULTAB for prediction case (no effect on results)

- operate/OPERATE-DEPTH.DATA
- operate/OPERATE-MULTZ.DATA
- operate/OPERATE-PERMZ.DATA
- operate/OPERATE-PORV.DATA
- operate/OPERATE-TRANX.DATA
- operate/OPERATE-TRANY.DATA
- operate/OPERATE-TRANZ.DATA
- operate/OPERATE.DATA
Remove RUNSUM keyword from all tests in preparation for future regression testing.
> OPERATER Keyword: Remove RUNSUM keyword from All Tests

- vfp/VFPINJ_WCONINJE-01.DATA
- vfp/include/summary.inc
Case includes 2 producers, 1 gas injector and 1 water injector. Both injectors are initially controlled with maximum surface rate. At the end of the simulation target surface rates are increased and both injectors end up being controlled by maximum tubing head pressure.
> Test case with VFP+WCONINJE

- model5/2B_GCONINJE_NETV_GAS.DATA
The purpose of this model is to verify that GCONINJE item10=NETV also works with gas injectors present (feature implemented in https://github.com/OPM/opm-simulators/pull/4460 ).
> Adding test model for GCONINJE item10=NETV with a gas injector

- spe1_solvent/SPE1CASE2_SOLVENT_FOAM.DATA
Test case where solvent and foam is tested based on SPE1CASE2_SOLVENT and _FOAM
See https://github.com/OPM/opm-simulators/pull/4654
> Add solvent + foam test

- weltraj/WELTRAJ-01.DATA
Depends on https://github.com/OPM/opm-common/pull/3465
> Add WELTRAJ test case

- spe1_solvent/SPE1CASE2_GASWATER_SOLVENT.DATA
Test case for
https://github.com/OPM/opm-simulators/pull/4568
> add Gas-water-solvent test case

- network/NETWORK-01_STANDARD.DATA
This test for Standard Network requires https://github.com/OPM/opm-common/pull/3609 and https://github.com/OPM/opm-simulators/pull/4760.
The figure shows a comparison with a reference simulator.
> Standard Network test

- winjdam/include/WINJDAM-SUMMARY.inc
support are added through PR https://github.com/OPM/opm-common/pull/3628 and https://github.com/OPM/opm-simulators/pull/4790 . 
Those PRs need to go in before this PR.
> adding filtration specific summary keywords to WINJDAM cases

- cskin/CSKIN-02.DATA
- cskin/CSKIN-03.DATA
- cskin/CSKIN-04.DATA
- cskin/CSKIN-05.DATA
These test cases convers different input for KH (item 8 in COMPDAT) and CSKIN used in combination with keyword WPIMULT and WELPI.
> Additional test cases for CSKIN

- co2store/CO2STORE_GW_DIRICHLET.DATA
Test case for DIRICHLET boundary condition. Made this test case for PR: https://github.com/OPM/opm-simulators/pull/4835
> Test case with DIRICHLET boundary condition

- udt/UDT-1D-01.DATA
- udt/UDT-1D-01B.DATA
- udt/UDT-1D-02.DATA
- udt/UDT-1D-03.DATA
This adds tests cases for UDT provided by @vkip
> add test cases for UDT

- network/NETWORK-01-REROUTE.DATA
- network/NETWORK-01-REROUTE_STD.DATA
Test cases for network reroute functionality in extended and standard network.
> Network reroute tests

- model2/0C_BASE_FBHPDEF.DATA
The keyword FBHPDEF is not supported in OPM Flow
> new test case with keyword FBHPDEF

- lgr/SPE1CASE1_CARFIN1.DATA
Currently, we support CpGrid with disjoint LGRs. A test has been added.
> Disjoint LGR test added

- pinch/T1B2_GAP.DATA
- pinch/T1B3_GAP.DATA
- pinch/T1B4_GAP.DATA
Test cases for PINCH with Item 4 set to all. All of these have permz and multz > 0.0 for the pinchout cells. This is currently not supported in OPM Flow.
> Additional test cases for pinch item4=all

- pyaction/PYACTION_WCONPROD_INSERT_KW.DATA
- pyaction/pyaction_wconprod_insert_kw.py
Simplified script, still produces the same output
> Simplify pyaction/pyaction_wconprod_insert_kw.py script

- aquifer-num/3D_1AQU_3CELLS_CHK_SATNUM.DATA
Specifically, checks that cells with a valid SATNUM specified in AQUNUM pass internal checks even with invalid values in input SATNUM array in the REGIONS section.
Ref https://github.com/OPM/opm-common/pull/4082
> Test to verify valid SATNUM in AQUNUM fixes any invalid SATNUM value

- pinch/T1B5_GAP.DATA
- pinch/T1B6_GAP.DATA
- pinch/T1B7_GAP.DATA
These are identical to T1B3 except that this includes MULTZ in schedule section.
> Two additional test cases with keyword pinch and item 4 = ALL

- minpv/MINPV300.DATA
Equals + MINPVV should remove 3 additional cells from the model Added one time step to the model in order to make the model run.
> added equals+minpvv to existing test model

- spe1/SPE1CASE2_GASWATER_THERMAL.DATA
This adds thermal effects to the existing SPE1CASE2_GASWATER.DATA. The primary intended usage is for development of a proof-of-concept for props and assembly on GPU, where our first target is SPE11-like gas/water/thermal simulation. Tests using this file may eventually be added.
> Add two-phase gas/water case with thermal.

- wcycle/WCYCLE-0.DATA
- wcycle/WCYCLE-1.DATA
- wcycle/WCYCLE-2.DATA
- wcycle/WCYCLE-3.DATA
- wcycle/WCYCLE-4.DATA
- wcycle/WCYCLE-5.DATA
- wcycle/WCYCLE-6.DATA
- wcycle/WCYCLE-7.DATA
- wcycle/WCYCLE-8.DATA
This tests multiple WCYCLE blocks and multi-well cycling.
> Add another WCYCLE test

- model5/6_UDA_MODEL5_STDW.DATA
- model5/include/summary_6uda.inc
Including UDAs for keywords GCONPROD, GCONINJE, WCONPROD and WCONINJE.
> Test case with UDAs

- satellite/GSATPROD2.DATA
This is GSATPROD1.DATA with the addition of GCONPROD
> Add test case with GSATPROD and GCONPROD

- network/NETWORK-01-WTEST.DATA
See https://github.com/OPM/opm-simulators/pull/6116
> Add test case for network + wtest

- msw/MSW-SIMPLE-1-SHUT-PERFORATION-BORDER.DATA
- msw/MSW-SIMPLE-SHUT-PERFORATIONS.DATA
For this, run the case with flow_distribute_z on 4 processes, the well PROD1 has 12 perforations, 5 on rank 0, 7 on rank 1.
> Add two tests with multisegment wells that are distributed across two processes and have shut perforations
